### PR TITLE
Fix handling of native python-gobject on Python 3

### LINKED ISSUE #168: TypeError: stat: path should be string, bytes, os.PathLike or integer, not list
if you run feedlint on a feed you get an error that a path should not be a list
the error message if from zeroinstall/injector/distro.py

```
feedlint mupdf.xml
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.7/0install", line 14, in <module>
    main(sys.argv[1:])
  File "/usr/lib/python3.7/site-packages/zeroinstall/cmd/__init__.py", line 381, in main
    cmd.handle(config, options, args)
  File "/usr/lib/python3.7/site-packages/zeroinstall/cmd/run.py", line 38, in handle
    sels = app.get_selections(may_update = True, use_gui = options.gui)
  File "/usr/lib/python3.7/site-packages/zeroinstall/apps.py", line 166, in get_selections
    sels = self._check_for_updates(sels, use_gui)
  File "/usr/lib/python3.7/site-packages/zeroinstall/apps.py", line 279, in _check_for_updates
    unavailable_selections = sels.get_unavailable_selections(config = self.config, include_packages = True)
  File "/usr/lib/python3.7/site-packages/zeroinstall/injector/selections.py", line 394, in get_unavailable_selections
    return [sel for sel in self.selections.values() if needs_download(sel)]
  File "/usr/lib/python3.7/site-packages/zeroinstall/injector/selections.py", line 394, in <listcomp>
    return [sel for sel in self.selections.values() if needs_download(sel)]
  File "/usr/lib/python3.7/site-packages/zeroinstall/injector/selections.py", line 385, in needs_download
    feed = iface_cache.get_feed(sel.feed)
  File "/usr/lib/python3.7/site-packages/zeroinstall/injector/iface_cache.py", line 367, in get_feed
    feed = self.distro.get_feed(master_feed)
  File "/usr/lib/python3.7/site-packages/zeroinstall/injector/distro.py", line 265, in get_feed
    _set_quick_test(impl, gobject.__path__)	        # Python 3
  File "/usr/lib/python3.7/site-packages/zeroinstall/injector/distro.py", line 29, in _set_quick_test
    impl.quick_test_mtime = int(os.stat(path).st_mtime)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not list
```

### PR DESCRIPTION
**Pull request by bastianeicher**
Fixes #168

### CODE REVIEW

**Review by talex5 — COMMENTED** [review]
I suspect it needs to check both cases (string and list). I guess the existing code works on some version of Python.

**Comment by bastianeicher** [comment]
I've adjusted the code accordingly.

**Comment by bastianeicher** [comment]
@talex5 Could you publish a new release of the 2.3.x branch incorporating this and #167?

**Comment by talex5** [comment]
Done!

**Pull request merged**
