### PR TITLE
Don't store may_compile attribute in selections unless it's explicitly given

### PR DESCRIPTION
**Pull request by gfxmonk**

### CODE REVIEW

**Comment by talex5** [comment]
Do we actually need an option wrapper here, or could we just not save it if it's `false`? As far as I can see, it can only be true during a `select` operation, which doesn't save anyway.

**Comment by gfxmonk** [comment]
Oops, good point. I thought that if you actually were to specify --may-compile=false, you'd want that saved (in case the default ever changed). But now I notice there's no argument to --may-compile, it just turns it on. So I'll get rid of the `option` wrapper.

**Comment by gfxmonk** [comment]
I've replaced this PR with two commits. The first omits `may_compile` if it's `false`, the second does the same for `source` and `extra_restrictions` when they match their defaults. The second commit doesn't fix any known problem (so feel free to ignore it), but seems nice and clean anyway.

**Comment by talex5** [comment]
Great - thanks!

**Pull request merged**
