### PR TITLE
Improve handling of libcurl dependency

### PR DESCRIPTION
**Pull request by bastianeicher**
List libcurl as dependency in feed and offer to automatically install in install script

### CODE REVIEW

**Comment by bastianeicher** [comment]
Good point. I've just updated the script to automatically prepend `sudo` to the package installation commands if it is available.

**Comment by bastianeicher** [comment]
Hmm, the Travis builds on MacOS are failing. Not sure why, but does not seem related to the install script.

**Comment by bastianeicher** [comment]
Rebased on current `master`. MacOS builds are passing now. :)

**Comment by talex5** [comment]
Thanks. I just tested it:

It didn't work for me on Debian. On my main machine, it didn't find `ldconfig` because it was in `/sbin/`.

Trying in a Docker container, it installed `libcurl3`, but then failed to run because the binary wanted `libcurl-gnutls.so.4` (which seems to be in the `libcurl3-gnutls` package). I guess we could parse the output of `ldd` to see what we need:

```
$ ldd files/0install
	linux-vdso.so.1 (0x00007ffc24723000)
	libcurl-gnutls.so.4 => not found
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x000078fbb2a8b000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x000078fbb2787000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x000078fbb2583000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x000078fbb21e4000)
	/lib64/ld-linux-x86-64.so.2 (0x000078fbb3602000)
```

Also, the libcurl dependency needs to be in `binary-feed.xml.in` too if you want to include it in the feed that `make` generates (this is to avoid a circular dependency between 0install and 0compile).

**Comment by bastianeicher** [comment]
Hmm, it's probably not a good idea to go poking around a machine's `/sbin` when running as non-root. Maybe it is the "right thing" for the script to just skip the check on machine's that don't have `ldconfig` in `PATH`?

The builds listed in http://0install.net/tools/0install.xml all seem to be compiled against the OpenSSL-version of `libcurl`, which is provided by the `libcurl3` package on Debian-based systems.  
The builds provided by the `0install-core` Debian package (as well as any manual builds performed on a Debian-based system I suppose) on the other hand are compiled against the GnuTLS-based version of `libcurl`, which is provided by the `libcurl3-gnuzls` package on Debian-based systems.

Parsing `ldd` output in the `install.sh` script seems a bit complicated to me. Maybe we could simply assume that this script will only be used for "official" 0install builds which are always built against the OpenSSL-version of `libcurl`?

**Comment by talex5** [comment]
> Parsing ldd output in the install.sh script seems a bit complicated to me.

I guess we could extract the dependencies (e.g. `libcurl-gnutls.so.4`) at build time, map them to package names on various platforms, and then put the results of that into the install script.

> Maybe we could simply assume that this script will only be used for "official" 0install builds which are always built against the OpenSSL-version of libcurl?

This script is run when anyone does `make install`.

**Comment by talex5** [comment]
The generic binaries no longer use libcurl. Should we close this PR?

**Comment by bastianeicher** [comment]
Agreed, no more need for this PR.

**Pull request closed without merging**
